# Generated by Django 5.2.7 on 2025-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
